# The location of your dagit console, e.g. "http://my-namespace-dagit/graphql"
dagitGraphQLUrl: ""

nodeSelector: {}

# params passed to LaunchPipelineExecution
executionParams:
  executionMetadata:
    tags: []
  mode: celery_k8s
  runConfigData:
    execution:
      multiprocess:
        config:
          max_concurrent: 4
    resources: {}
    solids:
      gridsearch_emit_run_configs:
        config: {}
  selector:
    pipelineName: ""
    repositoryLocationName: ""
    repositoryName: ""