# yaml-language-server: $schema=eksctlschema-0.73.0.json
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: dagster-eks-in-sml-vpc
  region: eu-west-1
  version: "1.21"

vpc:
  subnets:
    public:
      az1:
        id: null
      az2:
        id: null
      az3:
        id: null

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: cluster-autoscaler
      namespace: faculty-dagster
    wellKnownPolicies:
      autoScaler: true
  - metadata:
      name: aws-load-balancer-controller
      namespace: faculty-dagster
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: cloudwatch-grafana
      namespace: faculty-dagster
    attachPolicy: {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Sid": "AllowReadingMetricsFromCloudWatch",
          "Effect": "Allow",
          "Action": [
            "cloudwatch:DescribeAlarmsForMetric",
            "cloudwatch:DescribeAlarmHistory",
            "cloudwatch:DescribeAlarms",
            "cloudwatch:ListMetrics",
            "cloudwatch:GetMetricStatistics",
            "cloudwatch:GetMetricData",
            "cloudwatch:GetInsightRuleReport"
          ],
          "Resource": "*"
        },
        {
          "Sid": "AllowReadingLogsFromCloudWatch",
          "Effect": "Allow",
          "Action": [
            "logs:DescribeLogGroups",
            "logs:GetLogGroupFields",
            "logs:StartQuery",
            "logs:StopQuery",
            "logs:GetQueryResults",
            "logs:GetLogEvents"
          ],
          "Resource": "*"
        },
        {
          "Sid": "AllowReadingTagsInstancesRegionsFromEC2",
          "Effect": "Allow",
          "Action": ["ec2:DescribeTags", "ec2:DescribeInstances", "ec2:DescribeRegions"],
          "Resource": "*"
        },
        {
          "Sid": "AllowReadingResourcesForTags",
          "Effect": "Allow",
          "Action": "tag:GetResources",
          "Resource": "*"
        }
      ]
    }
managedNodeGroups:
  - name: dagster-c5-4xlarge
    instanceType: c5.4xlarge
    desiredCapacity: 0
    minSize: 0
    maxSize: 400
    labels:
      instanceGroup: dagster-c5-4xlarge
  - name: dagster-services
    instanceType: r5.4xlarge
    desiredCapacity: 1
    labels:
      instanceGroup: dagster-services
  - name: prometheus
    instanceType: c5.4xlarge
    desiredCapacity: 1
    availabilityZones:
      - 'eu-west-1a'
    labels:
      instanceGroup: prometheus
